language: node_js
sudo: false
notifications:
  irc:
    channels:
      - "irc.blitzed.org#stonecypher-builds"
    template:
      - "%{repository} %{build_number} (%{commit}) : %{message} %{foo} "
  recipients:
    - stonecypher@gmail.com
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
before_script: npm install
script: npm test